[project]
name = "adblock"
version = "0.0.0"
description = "Brave's adblocking in Python"
requires-python = ">=3.7"
authors = [
    {email = "arni@dagur.eu"},
    {name = "Árni Dagur"}
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
maturin = "*"
pytest = "*"
toml = "*"

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
